# roles/ROLENAME/tasks/main.yml
---
- name: install EPEL
  yum:
    name: epel-release
    state: present
- name: install Pound
  yum:
    name: Pound
    state: present
- name: empty "/etc/pound.cfg"
  blockinfile:
    dest: "/etc/pound.cfg"
    content: ""
- name: configure Load balancer
  blockinfile:
    dest: "/etc/pound.cfg"
    block: |
      virtual_alias_maps = ldap:/etc/postfix/ldap-aliases.cf
      local_recipient_maps = $alias_maps, ldap:/etc/postfix/ldap-users.cf
- name: add HTTP & HTTPS to the firewall
  firewalld:
    service: "http"
    permanent: true
    state: enabled
  with_items:
    - dhcpv6-client
    - ssh
  notify:
    - restart firewalld
  tags:
    - rhbase
    - security