# roles/ansible-role-pound/tasks/main.yml
---
- name: install EPEL
  yum:
    name: epel-release
    state: present
- name: install Pound
  yum:
    name: Pound
    state: present
- name: Install Pound configuration
  template:
    src: pound.cfg.j2
    dest: /etc/pound.cfg
  tags: pound
  notify:
    - restart pound
- name: add HTTP & HTTPS to the firewall
  firewalld:
    service: "http"
    permanent: true
    state: enabled
  with_items:
    - dhcpv6-client
    - ssh
  notify:
    - restart firewalld
  tags:
    - rhbase
    - security